import "./globals.css";
import Header from "./_components/Header";
import {Raleway} from "next/font/google"
import Footer from "./_components/Footer";
import { Toaster } from "@/components/ui/sonner";

const outift = Raleway({subsets: ["latin"]})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outift.className} antialiased`}
      >
        <div className="md:px-20">
          <Header />
          {children}
          <Toaster className='bg-slate-50'/>
        </div> 
        <Footer />
      </body>
    </html>
  );
}
